// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TriggerInitParameters struct {

	// asset notification_url. Default false.
	// When true, this global trigger fires in addition to any per-asset notification_url. Default false.
	Additive *bool `json:"additive,omitempty" tf:"additive,omitempty"`

	// (String) Signature method for verifying incoming webhook payloads. One of: default, legacy_hmac, eddsa_v2.
	// Signature method for verifying incoming webhook payloads. One of: default, legacy_hmac, eddsa_v2.
	AuthScheme *string `json:"authScheme,omitempty" tf:"auth_scheme,omitempty"`

	// (String) The event that fires the trigger. One of: upload, delete, rename, move, eager, explode, multi, resource_tags_changed, resource_context_changed, resource_metadata_changed, resource_display_name_changed, access_control_changed, related_assets, create_folder, delete_folder, move_or_rename_asset_folder, proof_status_changed, error, all.
	// The event that fires the trigger. One of: upload, delete, rename, move, eager, explode, multi, resource_tags_changed, resource_context_changed, resource_metadata_changed, resource_display_name_changed, access_control_changed, related_assets, create_folder, delete_folder, move_or_rename_asset_folder, proof_status_changed, error, all.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// encoded) that filters which events fire this trigger. When set, filter_language is automatically sent as "jsonlogic". Example: "{"==":[{"var":"resource_type"},"image"]}"
	// A JSONLogic expression (JSON-encoded) that filters which events fire this trigger. When set, filter_language is automatically sent as "jsonlogic". Example: "{\"==\":[{\"var\":\"resource_type\"},\"image\"]}"
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`

	// encoded, max 16KB) that customises the notification payload. Available namespaces: event, asset, folder, eager, error, raw.
	// A Mustache template object (JSON-encoded, max 16KB) that customises the notification payload. Available namespaces: event, asset, folder, eager, error, raw.
	PayloadTemplate *string `json:"payloadTemplate,omitempty" tf:"payload_template,omitempty"`

	// (String) The webhook URL to which Cloudinary sends the notification payload.
	// The webhook URL to which Cloudinary sends the notification payload.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type TriggerObservation struct {

	// asset notification_url. Default false.
	// When true, this global trigger fires in addition to any per-asset notification_url. Default false.
	Additive *bool `json:"additive,omitempty" tf:"additive,omitempty"`

	// (String) Signature method for verifying incoming webhook payloads. One of: default, legacy_hmac, eddsa_v2.
	// Signature method for verifying incoming webhook payloads. One of: default, legacy_hmac, eddsa_v2.
	AuthScheme *string `json:"authScheme,omitempty" tf:"auth_scheme,omitempty"`

	// (String) ISO 8601 timestamp of when the trigger was created.
	// ISO 8601 timestamp of when the trigger was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The event that fires the trigger. One of: upload, delete, rename, move, eager, explode, multi, resource_tags_changed, resource_context_changed, resource_metadata_changed, resource_display_name_changed, access_control_changed, related_assets, create_folder, delete_folder, move_or_rename_asset_folder, proof_status_changed, error, all.
	// The event that fires the trigger. One of: upload, delete, rename, move, eager, explode, multi, resource_tags_changed, resource_context_changed, resource_metadata_changed, resource_display_name_changed, access_control_changed, related_assets, create_folder, delete_folder, move_or_rename_asset_folder, proof_status_changed, error, all.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// encoded) that filters which events fire this trigger. When set, filter_language is automatically sent as "jsonlogic". Example: "{"==":[{"var":"resource_type"},"image"]}"
	// A JSONLogic expression (JSON-encoded) that filters which events fire this trigger. When set, filter_language is automatically sent as "jsonlogic". Example: "{\"==\":[{\"var\":\"resource_type\"},\"image\"]}"
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) The unique identifier of the trigger assigned by Cloudinary.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// encoded, max 16KB) that customises the notification payload. Available namespaces: event, asset, folder, eager, error, raw.
	// A Mustache template object (JSON-encoded, max 16KB) that customises the notification payload. Available namespaces: event, asset, folder, eager, error, raw.
	PayloadTemplate *string `json:"payloadTemplate,omitempty" tf:"payload_template,omitempty"`

	// (String) The product environment this trigger is scoped to.
	// The product environment this trigger is scoped to.
	ProductEnvironmentID *string `json:"productEnvironmentId,omitempty" tf:"product_environment_id,omitempty"`

	// (String) The webhook URL to which Cloudinary sends the notification payload.
	// The webhook URL to which Cloudinary sends the notification payload.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) The type of the URI. Always "webhook".
	// The type of the URI. Always "webhook".
	URIType *string `json:"uriType,omitempty" tf:"uri_type,omitempty"`

	// (String) ISO 8601 timestamp of when the trigger was last updated.
	// ISO 8601 timestamp of when the trigger was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type TriggerParameters struct {

	// asset notification_url. Default false.
	// When true, this global trigger fires in addition to any per-asset notification_url. Default false.
	// +kubebuilder:validation:Optional
	Additive *bool `json:"additive,omitempty" tf:"additive,omitempty"`

	// (String) Signature method for verifying incoming webhook payloads. One of: default, legacy_hmac, eddsa_v2.
	// Signature method for verifying incoming webhook payloads. One of: default, legacy_hmac, eddsa_v2.
	// +kubebuilder:validation:Optional
	AuthScheme *string `json:"authScheme,omitempty" tf:"auth_scheme,omitempty"`

	// (String) The event that fires the trigger. One of: upload, delete, rename, move, eager, explode, multi, resource_tags_changed, resource_context_changed, resource_metadata_changed, resource_display_name_changed, access_control_changed, related_assets, create_folder, delete_folder, move_or_rename_asset_folder, proof_status_changed, error, all.
	// The event that fires the trigger. One of: upload, delete, rename, move, eager, explode, multi, resource_tags_changed, resource_context_changed, resource_metadata_changed, resource_display_name_changed, access_control_changed, related_assets, create_folder, delete_folder, move_or_rename_asset_folder, proof_status_changed, error, all.
	// +kubebuilder:validation:Optional
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// encoded) that filters which events fire this trigger. When set, filter_language is automatically sent as "jsonlogic". Example: "{"==":[{"var":"resource_type"},"image"]}"
	// A JSONLogic expression (JSON-encoded) that filters which events fire this trigger. When set, filter_language is automatically sent as "jsonlogic". Example: "{\"==\":[{\"var\":\"resource_type\"},\"image\"]}"
	// +kubebuilder:validation:Optional
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`

	// encoded, max 16KB) that customises the notification payload. Available namespaces: event, asset, folder, eager, error, raw.
	// A Mustache template object (JSON-encoded, max 16KB) that customises the notification payload. Available namespaces: event, asset, folder, eager, error, raw.
	// +kubebuilder:validation:Optional
	PayloadTemplate *string `json:"payloadTemplate,omitempty" tf:"payload_template,omitempty"`

	// (String) The webhook URL to which Cloudinary sends the notification payload.
	// The webhook URL to which Cloudinary sends the notification payload.
	// +kubebuilder:validation:Optional
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

// TriggerSpec defines the desired state of Trigger
type TriggerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TriggerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TriggerInitParameters `json:"initProvider,omitempty"`
}

// TriggerStatus defines the observed state of Trigger.
type TriggerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TriggerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Trigger is the Schema for the Triggers API. Manages a Cloudinary webhook notification trigger. Triggers fire on specific asset events and POST a payload to a configured URL. Up to 30 triggers per product environment (the console UI shows only 10).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudinary}
type Trigger struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.eventType) || (has(self.initProvider) && has(self.initProvider.eventType))",message="spec.forProvider.eventType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.uri) || (has(self.initProvider) && has(self.initProvider.uri))",message="spec.forProvider.uri is a required parameter"
	Spec   TriggerSpec   `json:"spec"`
	Status TriggerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TriggerList contains a list of Triggers
type TriggerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Trigger `json:"items"`
}

// Repository type metadata.
var (
	Trigger_Kind             = "Trigger"
	Trigger_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Trigger_Kind}.String()
	Trigger_KindAPIVersion   = Trigger_Kind + "." + CRDGroupVersion.String()
	Trigger_GroupVersionKind = CRDGroupVersion.WithKind(Trigger_Kind)
)

func init() {
	SchemeBuilder.Register(&Trigger{}, &TriggerList{})
}
