//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPreset) DeepCopyInto(out *UploadPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPreset.
func (in *UploadPreset) DeepCopy() *UploadPreset {
	if in == nil {
		return nil
	}
	out := new(UploadPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UploadPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPresetInitParameters) DeepCopyInto(out *UploadPresetInitParameters) {
	*out = *in
	if in.AllowedFormats != nil {
		in, out := &in.AllowedFormats, &out.AllowedFormats
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AssetFolder != nil {
		in, out := &in.AssetFolder, &out.AssetFolder
		*out = new(string)
		**out = **in
	}
	if in.Eval != nil {
		in, out := &in.Eval, &out.Eval
		*out = new(string)
		**out = **in
	}
	if in.Moderation != nil {
		in, out := &in.Moderation, &out.Moderation
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Unsigned != nil {
		in, out := &in.Unsigned, &out.Unsigned
		*out = new(bool)
		**out = **in
	}
	if in.UseAssetFolderAsPublicIDPrefix != nil {
		in, out := &in.UseAssetFolderAsPublicIDPrefix, &out.UseAssetFolderAsPublicIDPrefix
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPresetInitParameters.
func (in *UploadPresetInitParameters) DeepCopy() *UploadPresetInitParameters {
	if in == nil {
		return nil
	}
	out := new(UploadPresetInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPresetList) DeepCopyInto(out *UploadPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UploadPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPresetList.
func (in *UploadPresetList) DeepCopy() *UploadPresetList {
	if in == nil {
		return nil
	}
	out := new(UploadPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UploadPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPresetObservation) DeepCopyInto(out *UploadPresetObservation) {
	*out = *in
	if in.AllowedFormats != nil {
		in, out := &in.AllowedFormats, &out.AllowedFormats
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AssetFolder != nil {
		in, out := &in.AssetFolder, &out.AssetFolder
		*out = new(string)
		**out = **in
	}
	if in.Eval != nil {
		in, out := &in.Eval, &out.Eval
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Moderation != nil {
		in, out := &in.Moderation, &out.Moderation
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Unsigned != nil {
		in, out := &in.Unsigned, &out.Unsigned
		*out = new(bool)
		**out = **in
	}
	if in.UseAssetFolderAsPublicIDPrefix != nil {
		in, out := &in.UseAssetFolderAsPublicIDPrefix, &out.UseAssetFolderAsPublicIDPrefix
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPresetObservation.
func (in *UploadPresetObservation) DeepCopy() *UploadPresetObservation {
	if in == nil {
		return nil
	}
	out := new(UploadPresetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPresetParameters) DeepCopyInto(out *UploadPresetParameters) {
	*out = *in
	if in.AllowedFormats != nil {
		in, out := &in.AllowedFormats, &out.AllowedFormats
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AssetFolder != nil {
		in, out := &in.AssetFolder, &out.AssetFolder
		*out = new(string)
		**out = **in
	}
	if in.Eval != nil {
		in, out := &in.Eval, &out.Eval
		*out = new(string)
		**out = **in
	}
	if in.Moderation != nil {
		in, out := &in.Moderation, &out.Moderation
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Unsigned != nil {
		in, out := &in.Unsigned, &out.Unsigned
		*out = new(bool)
		**out = **in
	}
	if in.UseAssetFolderAsPublicIDPrefix != nil {
		in, out := &in.UseAssetFolderAsPublicIDPrefix, &out.UseAssetFolderAsPublicIDPrefix
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPresetParameters.
func (in *UploadPresetParameters) DeepCopy() *UploadPresetParameters {
	if in == nil {
		return nil
	}
	out := new(UploadPresetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPresetSpec) DeepCopyInto(out *UploadPresetSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPresetSpec.
func (in *UploadPresetSpec) DeepCopy() *UploadPresetSpec {
	if in == nil {
		return nil
	}
	out := new(UploadPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadPresetStatus) DeepCopyInto(out *UploadPresetStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadPresetStatus.
func (in *UploadPresetStatus) DeepCopy() *UploadPresetStatus {
	if in == nil {
		return nil
	}
	out := new(UploadPresetStatus)
	in.DeepCopyInto(out)
	return out
}
