// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UploadPresetInitParameters struct {

	// The file formats Cloudinary accepts at upload time (e.g. ["pdf", "zip"]).
	AllowedFormats []*string `json:"allowedFormats,omitempty" tf:"allowed_formats,omitempty"`

	// The Cloudinary asset folder assets uploaded with this preset are placed in (e.g. "uaas-v2/file-uploader-preprod-eu/invoice").
	AssetFolder *string `json:"assetFolder,omitempty" tf:"asset_folder,omitempty"`

	// A server-side JavaScript snippet run by Cloudinary at upload time (e.g. to set moderation per file based on format).
	Eval *string `json:"eval,omitempty" tf:"eval,omitempty"`

	// The moderation mode applied to uploads (e.g. "manual"). For user-origin presets this is usually set dynamically by eval rather than statically.
	Moderation *string `json:"moderation,omitempty" tf:"moderation,omitempty"`

	// The name of the upload preset (e.g. "file-uploader-invoice"). Changing it forces a new preset.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The resource type Cloudinary applies. Defaults to "auto".
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The delivery type controlling asset access: "upload" (public URL), "authenticated" (token-signed delivery), or "private". Defaults to "upload".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Whether the preset allows unsigned uploads. Defaults to false (signed uploads).
	Unsigned *bool `json:"unsigned,omitempty" tf:"unsigned,omitempty"`

	// Whether Cloudinary prefixes the generated public_id with asset_folder. Defaults to true so minted public_ids start with the asset folder path. Relevant only when public_id_prefix/folder is not separately specified.
	UseAssetFolderAsPublicIDPrefix *bool `json:"useAssetFolderAsPublicIdPrefix,omitempty" tf:"use_asset_folder_as_public_id_prefix,omitempty"`
}

type UploadPresetObservation struct {

	// The file formats Cloudinary accepts at upload time (e.g. ["pdf", "zip"]).
	AllowedFormats []*string `json:"allowedFormats,omitempty" tf:"allowed_formats,omitempty"`

	// The Cloudinary asset folder assets uploaded with this preset are placed in (e.g. "uaas-v2/file-uploader-preprod-eu/invoice").
	AssetFolder *string `json:"assetFolder,omitempty" tf:"asset_folder,omitempty"`

	// A server-side JavaScript snippet run by Cloudinary at upload time (e.g. to set moderation per file based on format).
	Eval *string `json:"eval,omitempty" tf:"eval,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The moderation mode applied to uploads (e.g. "manual"). For user-origin presets this is usually set dynamically by eval rather than statically.
	Moderation *string `json:"moderation,omitempty" tf:"moderation,omitempty"`

	// The name of the upload preset (e.g. "file-uploader-invoice"). Changing it forces a new preset.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The resource type Cloudinary applies. Defaults to "auto".
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The delivery type controlling asset access: "upload" (public URL), "authenticated" (token-signed delivery), or "private". Defaults to "upload".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Whether the preset allows unsigned uploads. Defaults to false (signed uploads).
	Unsigned *bool `json:"unsigned,omitempty" tf:"unsigned,omitempty"`

	// Whether Cloudinary prefixes the generated public_id with asset_folder. Defaults to true so minted public_ids start with the asset folder path. Relevant only when public_id_prefix/folder is not separately specified.
	UseAssetFolderAsPublicIDPrefix *bool `json:"useAssetFolderAsPublicIdPrefix,omitempty" tf:"use_asset_folder_as_public_id_prefix,omitempty"`
}

type UploadPresetParameters struct {

	// The file formats Cloudinary accepts at upload time (e.g. ["pdf", "zip"]).
	// +kubebuilder:validation:Optional
	AllowedFormats []*string `json:"allowedFormats,omitempty" tf:"allowed_formats,omitempty"`

	// The Cloudinary asset folder assets uploaded with this preset are placed in (e.g. "uaas-v2/file-uploader-preprod-eu/invoice").
	// +kubebuilder:validation:Optional
	AssetFolder *string `json:"assetFolder,omitempty" tf:"asset_folder,omitempty"`

	// A server-side JavaScript snippet run by Cloudinary at upload time (e.g. to set moderation per file based on format).
	// +kubebuilder:validation:Optional
	Eval *string `json:"eval,omitempty" tf:"eval,omitempty"`

	// The moderation mode applied to uploads (e.g. "manual"). For user-origin presets this is usually set dynamically by eval rather than statically.
	// +kubebuilder:validation:Optional
	Moderation *string `json:"moderation,omitempty" tf:"moderation,omitempty"`

	// The name of the upload preset (e.g. "file-uploader-invoice"). Changing it forces a new preset.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The resource type Cloudinary applies. Defaults to "auto".
	// +kubebuilder:validation:Optional
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The delivery type controlling asset access: "upload" (public URL), "authenticated" (token-signed delivery), or "private". Defaults to "upload".
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Whether the preset allows unsigned uploads. Defaults to false (signed uploads).
	// +kubebuilder:validation:Optional
	Unsigned *bool `json:"unsigned,omitempty" tf:"unsigned,omitempty"`

	// Whether Cloudinary prefixes the generated public_id with asset_folder. Defaults to true so minted public_ids start with the asset folder path. Relevant only when public_id_prefix/folder is not separately specified.
	// +kubebuilder:validation:Optional
	UseAssetFolderAsPublicIDPrefix *bool `json:"useAssetFolderAsPublicIdPrefix,omitempty" tf:"use_asset_folder_as_public_id_prefix,omitempty"`
}

// UploadPresetSpec defines the desired state of UploadPreset
type UploadPresetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UploadPresetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UploadPresetInitParameters `json:"initProvider,omitempty"`
}

// UploadPresetStatus defines the observed state of UploadPreset.
type UploadPresetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UploadPresetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UploadPreset is the Schema for the UploadPresets API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudinary}
type UploadPreset struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   UploadPresetSpec   `json:"spec"`
	Status UploadPresetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UploadPresetList contains a list of UploadPresets
type UploadPresetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UploadPreset `json:"items"`
}

// Repository type metadata.
var (
	UploadPreset_Kind             = "UploadPreset"
	UploadPreset_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UploadPreset_Kind}.String()
	UploadPreset_KindAPIVersion   = UploadPreset_Kind + "." + CRDGroupVersion.String()
	UploadPreset_GroupVersionKind = CRDGroupVersion.WithKind(UploadPreset_Kind)
)

func init() {
	SchemeBuilder.Register(&UploadPreset{}, &UploadPresetList{})
}
