// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FolderInitParameters struct {

	// (String) The full path of the folder (e.g. "production/images"). Segments are separated by "/". Must not start or end with "/". Forbidden characters: ? & # \ % < >
	// The full path of the folder (e.g. "production/images"). Segments are separated by "/". Must not start or end with "/". Forbidden characters: ? & # \ % < >
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type FolderObservation struct {

	// (String) The folder's external ID assigned by Cloudinary. Use this value in Cedar policy statements (e.g. resource.ancestor_ids.contains("...")).
	// The folder's external ID assigned by Cloudinary. Use this value in Cedar policy statements (e.g. resource.ancestor_ids.contains("...")).
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (String) The folder's external ID assigned by Cloudinary (same as external_id).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The leaf name of the folder (the last component of the path).
	// The leaf name of the folder (the last component of the path).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The full path of the folder (e.g. "production/images"). Segments are separated by "/". Must not start or end with "/". Forbidden characters: ? & # \ % < >
	// The full path of the folder (e.g. "production/images"). Segments are separated by "/". Must not start or end with "/". Forbidden characters: ? & # \ % < >
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type FolderParameters struct {

	// (String) The full path of the folder (e.g. "production/images"). Segments are separated by "/". Must not start or end with "/". Forbidden characters: ? & # \ % < >
	// The full path of the folder (e.g. "production/images"). Segments are separated by "/". Must not start or end with "/". Forbidden characters: ? & # \ % < >
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

// FolderSpec defines the desired state of Folder
type FolderSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FolderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FolderInitParameters `json:"initProvider,omitempty"`
}

// FolderStatus defines the observed state of Folder.
type FolderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FolderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Folder is the Schema for the Folders API. Manages a Cloudinary folder. Folders are used to organize assets in your Cloudinary account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudinary}
type Folder struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.path) || (has(self.initProvider) && has(self.initProvider.path))",message="spec.forProvider.path is a required parameter"
	Spec   FolderSpec   `json:"spec"`
	Status FolderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FolderList contains a list of Folders
type FolderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Folder `json:"items"`
}

// Repository type metadata.
var (
	Folder_Kind             = "Folder"
	Folder_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Folder_Kind}.String()
	Folder_KindAPIVersion   = Folder_Kind + "." + CRDGroupVersion.String()
	Folder_GroupVersionKind = CRDGroupVersion.WithKind(Folder_Kind)
)

func init() {
	SchemeBuilder.Register(&Folder{}, &FolderList{})
}
